// The "1GIRL" Dataset - Source of Truth for Style Generation
export const PROMPT_DATABASE = [
`1girl, in a candid, Y2K-inspired street style photograph, two conventionally attractive young caucasian women with slender builds pose together on a city sidewalk...`,
`1girl, in a stylized promotional group photo exuding a vibrant hip-hop aesthetic on a hazy, smoke-filled studio stage...`,
`1girl, in a candid and energetic group mirror selfie capturing a moment of nightlife fun, five conventionally attractive young women...`,
`1girl, in a candid road trip selfie capturing a casual moment between two men inside the cab of a moving truck...`,
`1girl, in a candid nighttime group selfie capturing a casual nightlife vibe, a conventionally attractive young caucasian woman on the left...`,
`1girl, in a candid backstage group photo radiating a vibrant hip-hop and Y2K fashion aesthetic, a group of six conventionally attractive young Black adults...`,
`1girl, in a posed candid moment capturing a glam, influencer aesthetic at a baseball game, a conventionally attractive young caucasian woman is sitting...`,
`1girl, in a candid and vibrant street style moment captured amidst the chaotic energy of a crowded crosswalk, a conventionally attractive young caucasian woman...`,
`1girl, in a casual, candid-style promotional shot capturing two conventionally attractive young caucasian women at a grocery store checkout...`,
`1girl, in a celebratory and candid moment at an outdoor graduation, two conventionally attractive young caucasian women with slender builds...`,
`1girl, exuding a confident, edgy glam-punk vibe in a nighttime urban setting, is a beautiful young adult black woman...`,
`1girl, exuding a confident e-girl and Y2K grunge aesthetic in a modern architectural space...`,
`1girl, capturing a lo-fi, egirl aesthetic street style moment on a bustling city street at night...`,
`1girl, in a casual street style scene with a distinct Y2K aesthetic, a conventionally attractive young adult East Asian woman...`,
`1girl, in a casual and sunny vacation photo, a group of four conventionally attractive caucasian young adults...`,
`1girl, in a moment of pensive quietude that evokes a bohemian aesthetic, a beautiful young Black woman...`,
`1girl, in an edgy nighttime group portrait with a gritty, alternative vibe, a conventionally attractive young caucasian woman is the central figure...`,
`1girl, in a celebratory and joyful post-race scene, a group of three handsome, athletic young men...`,
`1girl, in a photo exuding a seductive e-girl aesthetic, a conventionally attractive young hispanic woman is sitting in a pink gaming chair...`,
`1girl, in a moody and intimate mirror selfie with a distinct e-girl aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, in a candid and sun-drenched summer scene capturing a social gathering of friends river tubing...`,
`1girl, in a playful and sexy influencer-style photo, a conventionally attractive young caucasian woman with a curvy build is posed sitting on a pink and white striped window seat...`,
`1girl, in a playful and casual mirror selfie with a male companion capturing a post-swim moment...`,
`1girl, in a staged, seductive late-night scene, a conventionally attractive young caucasian woman with a slender yet curvy build...`,
`1girl, in a celebratory and sensual party scene, two conventionally attractive young caucasian women pose together...`,
`1girl, in a chic street-style portrait exuding effortless confidence, this beautiful young adult Southeast Asian woman...`,
`1girl, exuding a confident, desert-chic aesthetic, a conventionally attractive young adult caucasian woman...`,
`1girl, embodying a casual e-girl and cosplay aesthetic in a bedroom setting, this conventionally attractive young caucasian woman...`,
`1girl, in a glamorous summer fashion portrait, a beautiful and conventionally attractive young adult woman...`,
`1girl, capturing a nightlife aesthetic in a posed outdoor shot at night, a conventionally attractive young Black woman...`,
`1girl, taking a posed mirror selfie with a friend in a gym environment to showcase their athletic physiques...`,
`1girl, in a casual and edgy road trip scene, a conventionally attractive young caucasian woman...`,
`1girl, in a sun-drenched vacation photo with a distinct beach aesthetic, a beautiful, conventionally attractive young caucasian woman...`,
`1girl, exuding a chic vacation vibe while dining at night on a rustic outdoor patio...`,
`1girl, exuding a stylish and sophisticated nightlife vibe, this beautiful, conventionally attractive young Black woman...`,
`1girl, embodying a provocative gamer-girl aesthetic in a meticulously staged streaming setup...`,
`1girl, in a casual sunbathing selfie, a conventionally attractive young caucasian woman is lying on her back...`,
`1girl, in a casual selfie with a bohemian vibe, a conventionally attractive young caucasian woman tilts her head...`,
`1girl, exuding a playful and sultry influencer-style aesthetic, a beautiful, conventionally attractive young caucasian woman...`,
`1girl, in a candid and casual nightlife scene captured while eating at a sushi restaurant...`,
`1girl, in a casual 'getting ready for a night out' mirror selfie featuring two conventionally attractive...`,
`1girl, exuding a glam, nightlife-ready vibe in what appears to be a bedroom, a conventionally attractive young caucasian woman...`,
`1girl, in a casual street style photo with an urban summer vibe, a conventionally attractive young woman...`,
`1girl, in a candid nightlife photo capturing a social gathering at a bar or restaurant...`,
`1girl, in a sun-drenched luxury beach club setting, a beautiful and conventionally attractive young adult caucasian...`,
`1girl, capturing the energetic, youthful atmosphere of an outdoor music festival...`,
`1girl, in a provocative e-girl aesthetic, a conventionally attractive young hispanic woman with a curvy build...`,
`1girl, capturing a casual and trendy y2k-aesthetic selfie in a public indoor space like a cafe...`,
`1girl, in a casual athleisure scene, a conventionally attractive young adult caucasian woman...`,
`1girl, in a casual gym mirror selfie with her partner, a conventionally attractive young caucasian...`,
`1girl, in a moody street-style tourist photo, a conventionally attractive young caucasian woman...`,
`1girl, in a candid, golden-hour moment with a chic street-style aesthetic, a conventionally attractive young adult woman...`,
`1girl, in a joyful and candid summer vibe scene, two conventionally attractive young caucasian women are captured eating...`,
`1girl, in a candid moment imbued with a tropical vacation vibe, a conventionally attractive young woman...`,
`1girl, in a casually posed social media-style photo, two conventionally attractive young caucasian women...`,
`1girl, in a candid and casual moment imbued with a Y2K aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, projecting an alternative, goth-inspired aesthetic in a posed selfie...`,
`1girl, in a casually posed social media-style photo, a conventionally attractive young caucasian woman...`,
`1girl, a conventionally attractive young caucasian woman, is captured mid-dance in a candid bedroom scene...`,
`1girl, in a provocative nightlife scene on a city street, is a conventionally attractive young adult woman...`,
`1girl, in a casual, street-style outdoor portrait with an influencer aesthetic, a conventionally attractive young adult Hispanic woman...`,
`1girl, in a candid and happy group photograph capturing a casual family celebration...`,
`1girl, capturing a candid, lo-fi mirror selfie with a distinct y2k digital camera aesthetic...`,
`1boy, in a casual, sponsored-athlete-style portrait, a handsome, conventionally attractive young caucasian man...`,
`1girl, in a casual and confident mirror selfie that showcases a fitspo aesthetic...`,
`1girl, in a vibrant tropical vacation setting, a beautiful young adult Black woman with a curvy build...`,
`1girl, in a candid moment captured inside a brightly lit, modern hair salon...`,
`1girl, in a modern, edgy street style portrait, a conventionally attractive young woman of East Asian descent...`,
`1girl, in a warm and casual golden-hour selfie with her partner...`,
`1girl, creating a playful yet provocative nightlife aesthetic, a conventionally attractive young woman...`,
`1girl, in a casual street style photo taken in a residential driveway, a conventionally attractive young adult hispanic woman...`,
`1girl, embodying a distinct y2k glam aesthetic, a conventionally attractive young hispanic woman...`,
`1girl, in a confident, street-style portrait, a conventionally attractive young woman of perceived Middle Eastern ethnicity...`,
`1girl, exuding a poised and elegant aura in traditional attire, is a beautiful, conventionally attractive young South Asian woman...`,
`1boy, in a casual snowboarding aesthetic, a handsome young caucasian or hispanic man...`,
`1girl, in a candid and playful moment during a night in with a friend that captures a fun, party-like atmosphere...`,
`1girl, embodying a seductive, "baddie" influencer aesthetic, a conventionally attractive young woman...`,
`1girl, in a provocative, influencer-style photo with a tropical vibe, is a conventionally attractive young adult caucasian woman...`,
`1girl, in a posed, candid-style photo with a seductive nightlife vibe, a conventionally attractive young caucasian...`,
`1girl, in a playful and candid tourist photo, a conventionally attractive young caucasian woman with a slender build...`,
`1girl, exuding a confident and sexy social media aesthetic, this conventionally attractive young Hispanic woman...`,
`1girl, in a candid moment within a surreal and psychedelic art installation, a conventionally attractive young East Asian woman...`,
`1girl, in a casual and sun-drenched selfie taken at a café, a conventionally attractive young caucasian woman...`,
`1girl, in a candid, lo-fi nightlife scene, a conventionally attractive young caucasian woman with a slender build...`,
`1girl, capturing a casual, y2k-inspired mirror selfie in a cluttered, warmly lit living room...`,
`1girl, in a casual and intimate at-home selfie, a beautiful and conventionally attractive young caucasian or hispanic woman...`,
`1girl, in a casual yet glamorous car selfie, a conventionally attractive young caucasian woman with a slender build...`,
`1girl, in a casual bedroom mirror selfie with a relaxed aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, embodying a bold Y2K street style aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, capturing a casual, y2k-inspired aesthetic in a candid mirror selfie...`,
`1girl, in a playfully eclectic and colorful living room defined by a maximalist, retro-inspired aesthetic...`,
`1girl, in a candid and pensive moment imbued with a distinct Y2K aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, in a candid and casual mirror selfie that captures a 'getting ready' moment in a messy bedroom...`,
`1girl, in a candid and trendy mirror selfie, a conventionally attractive young caucasian woman...`,
`1girl, in a candid vacation-style moment, a conventionally attractive young Caucasian or Hispanic woman...`,
`1girl, in a candid and casual mirror selfie capturing a moment of nightlife, a conventionally attractive young hispanic...`,
`1girl, in a confident and provocative mirror selfie designed for social media...`,
`1girl, in a casual mirror selfie with a distinct Y2K aesthetic, a conventionally attractive young caucasian woman...`,
`1girl, in a candid, sun-drenched street style photograph capturing a bustling Mediterranean vibe...`,
`1girl, in a casual yet opulent mirror selfie, a conventionally attractive young caucasian woman...`,
`1girl, in a moody and intimate bedroom selfie that channels a goth and Y2K aesthetic...`,
`1girl, in a candid vacation scene aboard a boat, a conventionally attractive young caucasian woman...`,
`1girl, in a surreal and humorous scene, a conventionally attractive young caucasian woman...`,
`1girl, exuding a defiant, casual music festival aesthetic, a conventionally attractive young Caucasian woman...`,
`1girl, in a photo with a distinct Y2K street style aesthetic, a conventionally attractive young caucasian woman...`
];